# -*- coding: utf-8 -*-
"""Aplicacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rgaZ6YzXqwa6lx0PdLEybU6qxwVyabNc
"""
import streamlit as st
import pandas as pd
import altair as alt
from streamlit_option_menu import option_menu

# Crear pagina
st.set_page_config(
    page_title="Visualización de datos de Salud de España",
    page_icon="⚕",
    layout="wide"
)

# Subir datos- metodo tomado de app de prueba de Streamlit
@st.cache_data
def load_data():
    df = pd.read_csv("datos/df_final.csv", encoding= "latin-1")
    return df

 #Se uso como referencia  https://www.youtube.com/watch?v=7E3yxq-P-a8
with st.sidebar:
    selected = option_menu(
        menu_title="Menú",
        options=["Inicio", "Ver resultados de la encuesta", "Predecir mi percepción de salud"],
        icons=["house-heart-fill", "clipboard-pulse", "stars"],
        menu_icon="body-text",
        default_index=0
    )

# Pagina de inicio
if selected == "Inicio":
    st.title("Análisis y Predicción de datos de Salud")
    st.subheader("Hola! 🤓")
    st.write("Gracias por tu interés por la salud en España.")
    st.write("""Esta página te permite visualizar resultados de la 
             [Encuesta de Salud de España 2023](https://www.sanidad.gob.es/estadEstudios/estadisticas/encuestaSaludEspana/home.htm).""")
    st.write("Usa el menu lateral para navegar entre: Visualización de datos y predicción de tu salud **percibida**.")
    st.subheader("Datos iniciales de la encuesta")

# Para ver los resultados

if selected == "Ver resultados de la encuesta":
    st.title("Ver resultados de la encuesta")
    st.write("Aqui encontrarás los resultados de la encuesta de salud de España 2023")
    st.subheader("🗺️ Haz clic en una comunidad autónoma")

# Cargar datos
    
    df = load_data()
    st.dataframe(df.head()) #https://www.youtube.com/watch?v=7E3yxq-P-a8

# Sección Predecir percepción de salud

if selected == "Predecir mi percepción de salud":
    st.title("Predecir mi percepción de salud")
    st.subheader("Aquí podrás predecir tu salud basado en los datos de la población en España")
    
# Entradas de los usuarions
    
    edad = st.slider("Selecciona tu edad", 0, 100, 25)
    st.write("Tu edad es:", edad)
    
    actividad = st.selectbox(
        "¿Cuál es tu nivel de actividad física?",
        ["Bajo", "Ocasional", "Regular", "Sedentario"]
    )
    
    if st.button("¡Predecir ahora!"):
        st.success("Predicción generada")
